# Generated by Django 5.1.2 on 2024-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='banda_larga_movel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='numero_utilizadores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='total_carregamentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='total_levantamentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='total_transferencias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
