# Generated by Django 5.1.2 on 2024-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0002_estacoesmoveisindicador_banda_larga_movel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='banda_larga_movel_3g_4g',
        ),
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_placas_box_banda_larga',
        ),
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_placas_usb_banda_larga',
        ),
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_servico_banda_larga',
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='banda_larga_movel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='numero_utilizadores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_carregamentos',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_levantamentos',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_transferencias',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
