# Generated by Django 5.1.2 on 2024-10-09 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_remove_estacoesmoveisindicador_banda_larga_movel_3g_4g_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafegoOriginadoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('trafego_dados_3g_upgrade', models.BigIntegerField(help_text='Em Mbit/s')),
                ('internet_3g', models.BigIntegerField(help_text='Em Mbit')),
                ('internet_3g_placas_modem', models.BigIntegerField(help_text='Em Mbit')),
                ('internet_3g_modem_usb', models.BigIntegerField(help_text='Em Mbit')),
                ('trafego_dados_4g', models.BigIntegerField(help_text='Em Mbit/s')),
                ('internet_4g', models.BigIntegerField(help_text='Em Mbyte (Mo)')),
                ('internet_4g_placas_modem', models.BigIntegerField(help_text='Em Mbyte (Mo)')),
                ('internet_4g_modem_usb', models.BigIntegerField(help_text='Em Mbyte (Mo)')),
                ('trafego_dados_2g', models.BigIntegerField(help_text='Em Sessões')),
                ('trafego_dados_3g_upgrade_sessoes', models.BigIntegerField(help_text='Em Sessões')),
                ('internet_3g_sessoes', models.BigIntegerField(help_text='Em Sessões')),
                ('internet_3g_placas_modem_sessoes', models.BigIntegerField(help_text='Em Sessões')),
                ('internet_3g_modem_usb_sessoes', models.BigIntegerField(help_text='Em Sessões')),
                ('sms_total', models.BigIntegerField(help_text='Número de mensagens enviadas')),
                ('sms_on_net', models.BigIntegerField()),
                ('sms_off_net', models.BigIntegerField()),
                ('sms_internacional', models.BigIntegerField()),
                ('sms_cedeao', models.BigIntegerField()),
                ('sms_palop', models.BigIntegerField()),
                ('sms_cplp', models.BigIntegerField()),
                ('sms_resto_africa', models.BigIntegerField()),
                ('sms_resto_mundo', models.BigIntegerField()),
                ('voz_total', models.BigIntegerField(help_text='Em minutos')),
                ('voz_on_net', models.BigIntegerField(help_text='Em minutos')),
                ('voz_off_net', models.BigIntegerField(help_text='Em minutos')),
                ('voz_mtn', models.BigIntegerField(help_text='Em minutos')),
                ('voz_internacional', models.BigIntegerField(help_text='Em minutos')),
                ('voz_cedeao', models.BigIntegerField(help_text='Em minutos')),
                ('voz_cplp', models.BigIntegerField(help_text='Em minutos')),
                ('voz_palop', models.BigIntegerField(help_text='Em minutos')),
                ('voz_resto_africa', models.BigIntegerField(help_text='Em minutos')),
                ('voz_resto_mundo', models.BigIntegerField(help_text='Em minutos')),
                ('chamadas_total', models.BigIntegerField(help_text='Número de chamadas')),
                ('chamadas_on_net', models.BigIntegerField()),
                ('chamadas_off_net', models.BigIntegerField()),
                ('chamadas_mtn', models.BigIntegerField()),
                ('chamadas_internacional', models.BigIntegerField()),
                ('chamadas_cedeao', models.BigIntegerField()),
                ('chamadas_cplp', models.BigIntegerField()),
                ('chamadas_palop', models.BigIntegerField()),
                ('chamadas_resto_africa', models.BigIntegerField()),
                ('chamadas_resto_mundo', models.BigIntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trafego_originado_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trafego_originado_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
