# Generated by Django 5.1.2 on 2024-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0004_trafegooriginadoindicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='numeros_curtos',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='operador_movel_b',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='operador_rede_fixa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
