# Generated by Django 5.1.2 on 2024-10-10 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0005_trafegooriginadoindicador_numeros_curtos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafegoTerminadoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('chamadas_outros_op_moveis_nacionais', models.BigIntegerField(help_text='De outros Operadores móveis nacionais (off-net)')),
                ('chamadas_mtn', models.BigIntegerField(help_text='MTN')),
                ('chamadas_operador_b', models.BigIntegerField(blank=True, help_text='Operador B', null=True)),
                ('chamadas_outros', models.BigIntegerField(blank=True, help_text='Outros (favor especificar)', null=True)),
                ('chamadas_operador_rede_fixa', models.BigIntegerField(blank=True, help_text='Operador da rede Fixa', null=True)),
                ('chamadas_cedeao', models.BigIntegerField(help_text='CEDEAO')),
                ('chamadas_cplp', models.BigIntegerField(help_text='CPLP')),
                ('chamadas_palop', models.BigIntegerField(help_text='PALOP')),
                ('chamadas_resto_africa', models.BigIntegerField(help_text='Resto de Africa')),
                ('chamadas_resto_mundo', models.BigIntegerField(help_text='Resto do mundo')),
                ('chamadas_numeros_curtos', models.BigIntegerField(help_text='N.º de chamadas de voz terminadas em números curtos e números não geográficos')),
                ('minutos_outros_op_moveis_nacionais', models.BigIntegerField(help_text='De outros operadores móveis nacionais (off-net)')),
                ('minutos_mtn', models.BigIntegerField(help_text='MTN')),
                ('minutos_operador_b', models.BigIntegerField(blank=True, help_text='Operador móvel B', null=True)),
                ('minutos_outros', models.BigIntegerField(blank=True, help_text='Outros (favor especificar)', null=True)),
                ('minutos_operador_rede_fixa', models.BigIntegerField(blank=True, help_text='Operador da rede Fixa', null=True)),
                ('minutos_cedeao', models.BigIntegerField(help_text='CEDEAO')),
                ('minutos_cplp', models.BigIntegerField(help_text='CPLP')),
                ('minutos_palop', models.BigIntegerField(help_text='PALOP')),
                ('minutos_resto_africa', models.BigIntegerField(help_text='Resto de Africa')),
                ('minutos_resto_mundo', models.BigIntegerField(help_text='Resto do mundo')),
                ('minutos_numeros_curtos', models.BigIntegerField(help_text='N.º de minutos de voz terminadas em números curtos e números não geográficos')),
                ('sms_outras_redes_moveis_nacionais', models.BigIntegerField(help_text='De outras redes móveis nacionais (off-net)')),
                ('sms_outras_redes_internacionais', models.BigIntegerField(help_text='De outras redes internacionais')),
                ('sms_outros', models.BigIntegerField(blank=True, help_text='Outros (Ex. serviços de valor acrescentado baseados no envio de mensagens)', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trafego_terminado_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trafego_terminado_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
