# Generated by Django 5.1.2 on 2024-10-10 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0008_lbiindicador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafegoInternetIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('trafego_total', models.DecimalField(decimal_places=2, help_text='Mbit/s', max_digits=15)),
                ('por_via_satelite', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('por_sistema_hertziano_fixo_terra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fibra_otica', models.DecimalField(decimal_places=2, max_digits=15)),
                ('banda_estreita_256kbps', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kbps_64_128', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kbps_128_256', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('banda_estreita_outros', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('banda_larga_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kbits_256_2mbits', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mbits_2_4', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mbits_10', models.DecimalField(decimal_places=2, max_digits=15)),
                ('banda_larga_outros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('residencial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('corporativo_empresarial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('instituicoes_publicas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('instituicoes_ensino', models.DecimalField(decimal_places=2, max_digits=15)),
                ('instituicoes_saude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ong_outros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cidade_bissau', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bafata', models.DecimalField(decimal_places=2, max_digits=15)),
                ('biombo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bolama_bijagos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cacheu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gabu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('oio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quinara', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tombali', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acesso_livre', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('acesso_condicionado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trafego_internet_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trafego_internet_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
