# Generated by Django 5.1.2 on 2024-10-10 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0009_trafegointernetindicador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetFixoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('cidade_bissau', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bafata', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('biombo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bolama_bijagos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cacheu', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gabu', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('oio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quinara', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tombali', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('airbox', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sistema_hertziano_fixo_terra', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('outros_proxim', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fibra_otica', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('banda_larga_256kbits_2mbits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('banda_larga_2_4mbits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('banda_larga_5_10mbits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('banda_larga_outros', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('residencial', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('corporativo_empresarial', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('instituicoes_publicas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('instituicoes_ensino', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('instituicoes_saude', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ong_outros', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internet_fixo_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internet_fixo_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador de Internet Fixo',
                'verbose_name_plural': 'Indicadores de Internet Fixo',
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
