# Generated by Django 5.1.2 on 2024-11-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0011_tarifariovozmtnindicador_tarifariovozorangeindicador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estacoesmoveisindicador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='internetfixoindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='lbiindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='tarifariovozorangeindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='trafegointernetindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='trafegoroaminginternacionalindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='trafegoterminadoindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterUniqueTogether(
            name='estacoesmoveisindicador',
            unique_together={('ano', 'mes', 'operadora')},
        ),
    ]
