# Generated by Django 5.1.2 on 2024-11-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0012_alter_estacoesmoveisindicador_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internetfixoindicador',
            unique_together={('ano', 'mes', 'operadora')},
        ),
        migrations.AlterUniqueTogether(
            name='lbiindicador',
            unique_together={('ano', 'mes', 'operadora')},
        ),
        migrations.AlterUniqueTogether(
            name='trafegointernetindicador',
            unique_together={('ano', 'mes', 'operadora')},
        ),
        migrations.AlterUniqueTogether(
            name='trafegooriginadoindicador',
            unique_together={('ano', 'mes', 'operadora')},
        ),
        migrations.AlterUniqueTogether(
            name='trafegoroaminginternacionalindicador',
            unique_together={('ano', 'mes', 'operadora')},
        ),
        migrations.AlterUniqueTogether(
            name='trafegoterminadoindicador',
            unique_together={('ano', 'mes', 'operadora')},
        ),
    ]
