# Generated by Django 5.1.2 on 2024-11-07 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0014_receitasindicador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpregoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('operadora', models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora')),
                ('emprego_direto_total', models.IntegerField(verbose_name='Total do emprego directo')),
                ('nacionais_total', models.IntegerField(verbose_name='Nacionais - Total')),
                ('nacionais_homem', models.IntegerField(verbose_name='Nacionais - Homem')),
                ('nacionais_mulher', models.IntegerField(verbose_name='Nacionais - Mulher')),
                ('emprego_indireto', models.IntegerField(verbose_name='Total do emprego indirecto (Agentes, distribuidores, etc.)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprego_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprego_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emprego',
                'verbose_name_plural': 'Empregos',
                'unique_together': {('ano', 'mes', 'operadora')},
            },
        ),
    ]
