# Generated by Django 5.1.2 on 2024-11-13 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0015_empregoindicador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestimentoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('operadora', models.CharField(blank=True, choices=[('orange', 'Orange'), ('mtn', 'MTN')], max_length=10, null=True, verbose_name='Operadora')),
                ('servicos_telecomunicacoes', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Serviços de Telecomunicações')),
                ('servicos_internet', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Serviços de Internet')),
                ('servicos_telecomunicacoes_incorporeo', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Serviços de Telecomunicações (Incorpóreo)')),
                ('servicos_internet_incorporeo', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Serviços de Internet (Incorpóreo)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('outros_investimentos', models.JSONField(blank=True, help_text='Campos adicionais de investimentos', null=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimento_atualizado', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investimento_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador de Investimento',
                'verbose_name_plural': 'Indicadores de Investimento',
                'unique_together': {('ano', 'mes', 'operadora')},
            },
        ),
    ]
